# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 16:37
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='warsaw.City')),
            ],
        ),
        migrations.CreateModel(
            name='GreenRoof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roof_address', models.CharField(max_length=256)),
                ('roof_type', models.IntegerField(choices=[(1, 'intensive'), (2, 'semi-intensive'), (3, 'extensive'), (4, 'biosolar')], verbose_name='Green roof type: ')),
                ('area', models.FloatField()),
                ('total_place_area', models.FloatField()),
                ('access', models.IntegerField(choices=[(1, 'yes'), (2, 'no')], verbose_name='Accessability: ')),
                ('ownership_type', models.IntegerField(choices=[(1, 'private'), (2, 'public')], verbose_name='Type of the building: ')),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='warsaw.District')),
            ],
            options={
                'verbose_name': 'Green roof',
                'verbose_name_plural': 'Green roofs',
            },
        ),
    ]
