# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warsaw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenroof',
            name='additional_info',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warsaw.City'),
        ),
        migrations.AlterField(
            model_name='greenroof',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warsaw.District'),
        ),
    ]
