# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 07:56
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warsaw', '0010_rental'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rental',
        ),
        migrations.AlterField(
            model_name='greenroof',
            name='poly',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
