# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 14:24
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warsaw', '0012_auto_20170407_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenroof',
            name='access',
            field=models.IntegerField(choices=[(1, 'yes'), (2, 'no')], verbose_name='Accessability'),
        ),
        migrations.AlterField(
            model_name='greenroof',
            name='ownership_type',
            field=models.IntegerField(choices=[(1, 'private'), (2, 'public')], verbose_name='Type of the building'),
        ),
        migrations.AlterField(
            model_name='greenroof',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Pin the place or search by address'),
        ),
        migrations.AlterField(
            model_name='greenroof',
            name='roof_type',
            field=models.IntegerField(choices=[(1, 'intensive'), (2, 'semi-intensive'), (3, 'extensive'), (4, 'biosolar')], verbose_name='Green roof type'),
        ),
    ]
