# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 09:39
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warsaw', '0013_auto_20170412_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenroof',
            name='poly',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='Pin the green roof area to create a polygon'),
        ),
    ]
