# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 20:07
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roof_type', models.IntegerField(choices=[(1, 'intensywny'), (2, 'półintensywny'), (3, 'ekstensywny'), (4, 'biosolarny')], verbose_name='Typ zielonego dachu: ')),
                ('name', models.CharField(max_length=128)),
                ('roof_address', models.CharField(max_length=256)),
                ('area', models.IntegerField()),
                ('access', models.IntegerField(choices=[(1, 'tak'), (2, 'nie')], verbose_name='Dostępność: ')),
                ('ownership', models.IntegerField(choices=[(1, 'private'), (2, 'public')], verbose_name='Rodzaj budynku: ')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'Wola',
            },
        ),
    ]
